config/routes.rb
Rails.application.routes.draw do
  
  root 'paintings#index'

  resources :paintings, only: [:index, :show]
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  
  serialize :colors, JSON 
  serialize :small_image, JSON
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  
  def index
    @paintings = Painting.paginate(:page => params[:page], :per_page => 10)
  end
    
    
  def create
  end
    
  def show
    @painting = Painting.find(params[:id])
  rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'Het schilderij dat u zoekt, kan niet gevonden worden'
      redirect_to paintings_path
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>Proefopdracht - Roelof Wobben</title>
    
    <%= stylesheet_link_tag    'aurora-pack.css', 'aurora-theme-base.css', 'urku.css', 'pagination.css'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  
  <% flash.each do |key, message| %>
    <div><%= message %></div>
  <% end %>
  
  <%= yield %>
    
</html>

app/views/paintings/index.html.erb
<body class="top-fixed">
  <header class="ae-container-fluid ae-container-fluid--full rk-header ">
    <div class="ae-container-fluid rk-topbar">
      <h1 class="rk-logo"> <%= link_to "Rijksmuseum - De topstukken van de schilderijen", root_url %> </h1>
    </div>
    </header>
    <section class="ae-container-fluid rk-main">
      <section class="ae-container-fluid ae-container-fluid--inner rk-portfolio">
        <div class="ae-masonry ae-masonry-md-2 ae-masonry-xl-3">
          
          <% @paintings.each do |painting| %>
            <%= link_to painting_path(painting), class: 'rk-item ae-masonry__item' do %>
              <%= image_tag painting.small_image["tiles"].first["url"] %>
              <div class="item-meta">
                <h2><%= painting.name %></h2>
                <p><%= painting.title %></p>
              </div>
            <% end %>
          <% end %>
        </div>
       <%= will_paginate @paintings %>
      </section>
    </section>  
</body>
 
 

app/views/paintings/show.html.erb
<body class="top-fixed" style= "background-image: url(<%= @painting.small_image["tiles"].first["url"] %> ); background-size: cover ">
  <div class="ae-container-fluid2 ae-container-fluid--inner2 rk-main">
    <div class="ae-grid au-xs-ta-left au-mb-4">
      <div class="ae-grid__item item-lg-2 ae-kappa au-mb-1" style= "background-color: rgba(255,255,255,0.2); height:120px">
        <p class=" au-mb-3" style="text-align: center"><%= @painting.title %></p>
        <p class=" au-mb-3" style="text-align: center"><%= @painting.name %></p>
      </div>
      <div class="ae-grid__item item-lg-8 ae-kappa au-mb-6">
      </div>  
      <div class="ae-grid__item item-lg-2 ae-kappa au-mb-1" style = "background-color: white; border: 1px solid ">
        <h5 class="ae-u-bolder au-mt-2" style = "text-align: center">Details</h5>
        <p class="au-mb-3 au-pl-4 au-pr-4">
          Collectie        : <%= @painting.collectie %> </br>
          Datering         : <%= @painting.date %></br>
          Primaire kleuren : </br>
          <% @painting.colors.each  do |color|  %>
            <span class = "box" style = "background-color:  <%= color %>">  </span>
          <% end %>    
          </br></br>
          Omschrijving  : </br>
            <%= @painting.description %>
        </p>  
      </div>
    </div>
  </div>
</body>    